name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: List changed files
        id: changed_files
        run: |
          echo "Listing changed files..."
          git fetch origin main 
          git diff --name-only origin/main > changed_files.txt
          cat changed_files.txt

      - name: Upload to FTP
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          while IFS= read -r file; do
            echo "Uploading $file..."
            dir=$(dirname "$file")
            lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" << EOF
              mkdir -p $dir
              put -O $dir $file
              bye
EOF
          done < changed_files.txt
