name: Deploy to FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: List changed files
        id: changed_files
        run: |
          echo "Listing changed files..."
          git fetch origin main 
          git diff --name-only origin/main > changed_files.txt
          cat changed_files.txt

      - name: Copy changed files
        run: |
          mkdir -p temp_upload_dir
          while IFS= read -r file; do
            mkdir -p "temp_upload_dir/$(dirname "$file")"
            cp "$file" "temp_upload_dir/$file"
          done < changed_files.txt

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: temp_upload_dir  
          remote-dir: /  
          extra-args: "--ignore-time --recursive"
