name: Merge main to stg and tst

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  merge-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge main into tst
        run: |
          git checkout tst
          git merge main --no-ff -m "Auto-merge main into tst"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} tst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main into stg
        run: |
          git checkout stg
          git merge main --no-ff -m "Auto-merge main into stg"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} stg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
