name: Sync branch

on:
  push:
    branches:
      - '*'
jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Merge main > tst
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: tst
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main > stg
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: stg
          github_token: ${{ secrets.GITHUB_TOKEN }}